# Generated by Django 4.1.2 on 2022-10-31 15:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_alter_product_options_basket'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='basket',
            name='available',
        ),
        migrations.RemoveField(
            model_name='basket',
            name='created',
        ),
        migrations.RemoveField(
            model_name='basket',
            name='description',
        ),
        migrations.RemoveField(
            model_name='basket',
            name='updated',
        ),
    ]
