# Generated by Django 4.1.2 on 2022-10-31 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_remove_basket_available_remove_basket_created_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='basket',
            options={'ordering': ['name'], 'verbose_name': 'Корзина', 'verbose_name_plural': 'Товары в корзине'},
        ),
        migrations.AddField(
            model_name='basket',
            name='value',
            field=models.PositiveIntegerField(blank=True, default=1),
            preserve_default=False,
        ),
    ]
