# Generated by Django 4.1.2 on 2022-11-07 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0005_remove_basket_category_remove_basket_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='basket',
            name='slug',
            field=models.SlugField(blank=True, max_length=200),
        ),
    ]
