# Generated by Django 4.1.2 on 2022-11-07 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0006_basket_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='basket',
            name='user_of',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
