# Generated by Django 4.1.2 on 2022-11-08 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0007_basket_user_of'),
    ]

    operations = [
        migrations.AddField(
            model_name='basket',
            name='image',
            field=models.ImageField(blank=True, upload_to='products/%Y/%m/%d'),
        ),
    ]
